import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistNunito = Nunito_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistNunito.variable} antialiased`}
      >
        <main className="bg-gray-100 min-h-screen">
          <nav className="bg-white w-full h-16 flex items-center justify-center">
            <section className="container flex items-center gap-3">
              <Image 
                src={"/Emoji.svg"}
                alt="Logo da aplicação"
                width={48}
                height={48}
              />
              <h1 className="text-2xl font-bold">Lista de países</h1>
            </section>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
